version: '3.8'

services:

  db:
    image: mariadb:10.6
    container_name: glpi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpiuser
      MYSQL_PASSWORD: glpipassword
    volumes:
      - db_data:/var/lib/mysql

  glpi:
    image: diouxx/glpi
    container_name: glpi_app
    restart: always
    ports:
      - "8080:80"
    environment:
      - TIMEZONE=America/Toronto
    depends_on:
      - db
    volumes:
      - glpi_data:/var/www/html

volumes:
  db_data:
  glpi_data:

